"""empty message

Revision ID: f2e15ebf3a1d
Revises: 52c2c795f1ff
Create Date: 2020-04-28 01:22:42.773814

"""
from alembic import op
import sqlalchemy as sa
import sys

sys.path.append("../../")
import app
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = "f2e15ebf3a1d"
down_revision = "52c2c795f1ff"
branch_labels = None
depends_on = None

genre_type = ENUM(
    "jazz",
    "classical",
    "reggae",
    "swing",
    "folk",
    "r_b",
    "hip_hop",
    "rock_n_roll",
    name="genre_type",
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    genre_type.create(op.get_bind())
    op.add_column(
        "Venue", sa.Column("genres", app.ArrayOfEnum(genre_type), nullable=True,),
    )
    op.add_column("Venue", sa.Column("seeking_description", sa.Text(), nullable=True))
    op.add_column("Venue", sa.Column("seeking_talent", sa.Boolean(), nullable=True))
    op.add_column("Venue", sa.Column("website", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Venue", "website")
    op.drop_column("Venue", "seeking_talent")
    op.drop_column("Venue", "seeking_description")
    op.drop_column("Venue", "genres")
    genre_type.drop(op.get_bind())
    # ### end Alembic commands ###
